name: getter

on:
  schedule:
    - cron:  '*/5 * * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Trick Garry for $$$
        run: |
          echo " " >> README.md
          git config user.name {USERNAME}
          git config user.email {EMAIL}
          git add .
          git commit -m "Always green!"
          git push
