name: Update

on:
  schedule:
    - cron:  '*/5 * * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: The update
        run: |
          echo " " >> README.md
          git config user.name
          git config user.email
          git add .
          git commit -m "Updates"
          git push